In [2]:
import pandas as pd

# 1. Load a CSV file

In [9]:
# 1. Basic Import. The standard way to load a CSV.
df = pd.read_csv('students.csv')

In [10]:
df

      Name  Age  Grade      City
0    Alice   20     85    Boston
1      Bob   19     92  New York
2  Charlie   21     78   Chicago
3    Diana   20     88    Boston
4      Eve   22     95   Seattle
5    Frank   19     82     Miami
6    Grace   21     90    Denver
7    Henry   20     76    Austin
8     Iris   22     89  Portland
9     Jack   19     84   Phoenix

In [11]:
?pd.read_csv

In [14]:
df

         Age  Grade      City
Name
Alice     20     85    Boston
Bob       19     92  New York
Charlie   21     78   Chicago
Diana     20     88    Boston
Eve       22     95   Seattle
Frank     19     82     Miami
Grace     21     90    Denver
Henry     20     76    Austin
Iris      22     89  Portland
Jack      19     84   Phoenix

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Student   10 non-null     str
 1   Years     10 non-null     int64
 2   Score     10 non-null     int64
 3   Location  10 non-null     str
dtypes: int64(2), str(2)
memory usage: 452.0 bytes

In [18]:
# 2. Changing the Delimiter (sep)
# If your file uses a semicolon (;) or tab (\t) instead of a comma.
# Assuming the file used semicolons
df = pd.read_csv('students.csv', sep=',')

In [22]:
df

      Name  Grade
0    Alice     85
1      Bob     92
2  Charlie     78
3    Diana     88
4      Eve     95
5    Frank     82
6    Grace     90
7    Henry     76
8     Iris     89
9     Jack     84

In [19]:
# 3. Setting a Column as the Index (index_col)
# If you want to use a specific column (like Name) as the row identifier instead of the default numeric index.
df = pd.read_csv('students.csv', index_col ='Name')

In [23]:
df

      Name  Grade
0    Alice     85
1      Bob     92
2  Charlie     78
3    Diana     88
4      Eve     95
5    Frank     82
6    Grace     90
7    Henry     76
8     Iris     89
9     Jack     84

In [20]:
# 4. Selecting Specific Columns (usecols)
# Useful when you have a massive dataset and only need a few specific columns, which saves memory.
df = pd.read_csv('students.csv',usecols=['Name', 'Grade'])

In [21]:
df

      Name  Grade
0    Alice     85
1      Bob     92
2  Charlie     78
3    Diana     88
4      Eve     95
5    Frank     82
6    Grace     90
7    Henry     76
8     Iris     89
9     Jack     84

In [24]:
# 5. Renaming Columns on Import (names)
# Use this to overwrite the headers or if the file has no header row. 
# You must set header=0 (to skip the original) if you want to replace it.
df = pd.read_csv('students.csv', names=['Student', 'Years', 'Score', 'Location'], header =0)

In [25]:
df

   Student  Years  Score  Location
0    Alice     20     85    Boston
1      Bob     19     92  New York
2  Charlie     21     78   Chicago
3    Diana     20     88    Boston
4      Eve     22     95   Seattle
5    Frank     19     82     Miami
6    Grace     21     90    Denver
7    Henry     20     76    Austin
8     Iris     22     89  Portland
9     Jack     19     84   Phoenix

In [29]:
# 6. Defining Data Types (dtype)
# You can force a column to be a specific type (e.g., Age as a float or Name as a category) to optimize performance.
df = pd.read_csv('students.csv', dtype={'Age':'float', 'Grade':'float'})

In [30]:
df

      Name   Age  Grade      City
0    Alice  20.0   85.0    Boston
1      Bob  19.0   92.0  New York
2  Charlie  21.0   78.0   Chicago
3    Diana  20.0   88.0    Boston
4      Eve  22.0   95.0   Seattle
5    Frank  19.0   82.0     Miami
6    Grace  21.0   90.0    Denver
7    Henry  20.0   76.0    Austin
8     Iris  22.0   89.0  Portland
9     Jack  19.0   84.0   Phoenix

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     str
 1   Age     10 non-null     float64
 2   Grade   10 non-null     float64
 3   City    10 non-null     str
dtypes: float64(2), str(2)
memory usage: 452.0 bytes

In [32]:
# 7. Limiting the Number of Rows (nrows)
# Best for testing code on large datasets without reading the entire file.
# Read only the first 5 rows
df = pd.read_csv('students.csv',nrows=5)

In [33]:
df

      Name  Age  Grade      City
0    Alice   20     85    Boston
1      Bob   19     92  New York
2  Charlie   21     78   Chicago
3    Diana   20     88    Boston
4      Eve   22     95   Seattle

In [34]:
# 8. Skipping Rows (skiprows)
# Useful if your CSV file has descriptive text or metadata at the top that isn't part of the actual data.
# Skip the first 2 lines of the file
df = pd.read_csv('students.csv', skiprows=2)

In [36]:
df

       Bob  19  92  New York
0  Charlie  21  78   Chicago
1    Diana  20  88    Boston
2      Eve  22  95   Seattle
3    Frank  19  82     Miami
4    Grace  21  90    Denver
5    Henry  20  76    Austin
6     Iris  22  89  Portland
7     Jack  19  84   Phoenix

In [42]:
df = pd.read_csv('students.csv')

In [43]:
cols_names = df.columns

In [46]:
df = pd.read_csv('students.csv', skiprows=3, names=cols_names)

In [47]:
df

      Name  Age  Grade      City
0  Charlie   21     78   Chicago
1    Diana   20     88    Boston
2      Eve   22     95   Seattle
3    Frank   19     82     Miami
4    Grace   21     90    Denver
5    Henry   20     76    Austin
6     Iris   22     89  Portland
7     Jack   19     84   Phoenix

In [50]:
# 9. Handling Missing Values (na_values)
# If your data represents "empty" or "unknown" entries with specific strings like "N/A" or "None", 
# you can tell pandas to treat them as NaN (Not a Number).
df = pd.read_csv('students_updated.csv', na_values=['N/A', 'unknowkn'])

In [51]:
df

       Name   Age  Grade          City              EnrollmentDate
0     Alice  20.0   85.0        Boston                         NaN
1       Bob  19.0   92.0      New York                         NaN
2   Charlie  21.0   78.0       Chicago                         NaN
3     Diana  20.0   88.0        Boston                         NaN
4       Eve  22.0   95.0       Seattle                         NaN
5     Frank  19.0   82.0         Miami                         NaN
6     Grace  21.0   90.0        Denver                         NaN
7     Henry  20.0   76.0        Austin                         NaN
8      Iris  22.0   89.0      Portland                         NaN
9      Jack  19.0   84.0       Phoenix                         NaN
10    Frank   NaN   92.0   Los Angeles  2026-06-18 14:48:35.126842
11    Grace  21.0   80.0         Miami  2026-06-17 14:48:35.126924
12    Heidi  22.0    NaN       Houston  2026-06-16 14:48:35.126928
13     Ivan  24.0   93.0       Phoenix  2026-06-15 14:48:35.126930
14     Judy  20.0   90.0        Dallas  2026-06-14 14:48:35.126932
15    Kevin  22.0   73.0           NaN  2026-06-13 14:48:35.126933
16     Liam  22.0   77.0        Austin  2026-06-12 14:48:35.126935
17      Mia  24.0   93.0  Jacksonville  2026-06-11 14:48:35.126936
18     Noah  19.0   72.0      Columbus  2026-06-10 14:48:35.126938
19   Olivia  20.0   91.0     Charlotte  2026-06-09 14:48:35.126939

In [52]:
# 10. Parsing Dates (parse_dates)
# If you had a date column (e.g., 'EnrollmentDate'), this would automatically convert those strings 
# into actual datetime objects.
df = pd.read_csv('students_updated.csv', parse_dates=['EnrollmentDate'])

In [53]:
df

       Name   Age  Grade          City             EnrollmentDate
0     Alice  20.0   85.0        Boston                        NaT
1       Bob  19.0   92.0      New York                        NaT
2   Charlie  21.0   78.0       Chicago                        NaT
3     Diana  20.0   88.0        Boston                        NaT
4       Eve  22.0   95.0       Seattle                        NaT
5     Frank  19.0   82.0         Miami                        NaT
6     Grace  21.0   90.0        Denver                        NaT
7     Henry  20.0   76.0        Austin                        NaT
8      Iris  22.0   89.0      Portland                        NaT
9      Jack  19.0   84.0       Phoenix                        NaT
10    Frank   NaN   92.0   Los Angeles 2026-06-18 14:48:35.126842
11    Grace  21.0   80.0         Miami 2026-06-17 14:48:35.126924
12    Heidi  22.0    NaN       Houston 2026-06-16 14:48:35.126928
13     Ivan  24.0   93.0       Phoenix 2026-06-15 14:48:35.126930
14     Judy  20.0   90.0        Dallas 2026-06-14 14:48:35.126932
15    Kevin  22.0   73.0           NaN 2026-06-13 14:48:35.126933
16     Liam  22.0   77.0        Austin 2026-06-12 14:48:35.126935
17      Mia  24.0   93.0  Jacksonville 2026-06-11 14:48:35.126936
18     Noah  19.0   72.0      Columbus 2026-06-10 14:48:35.126938
19   Olivia  20.0   91.0     Charlotte 2026-06-09 14:48:35.126939

In [54]:
# 2. Check for nulls
df.isnull().sum()

Name               0
Age                1
Grade              1
City               1
EnrollmentDate    10
dtype: int64

In [55]:
# 3. Handle nulls (e.g., fill with the mean)
df['Age'] = df ['Age'].fillna(df['Age'].mean())

In [56]:
df

       Name        Age  Grade          City             EnrollmentDate
0     Alice  20.000000   85.0        Boston                        NaT
1       Bob  19.000000   92.0      New York                        NaT
2   Charlie  21.000000   78.0       Chicago                        NaT
3     Diana  20.000000   88.0        Boston                        NaT
4       Eve  22.000000   95.0       Seattle                        NaT
5     Frank  19.000000   82.0         Miami                        NaT
6     Grace  21.000000   90.0        Denver                        NaT
7     Henry  20.000000   76.0        Austin                        NaT
8      Iris  22.000000   89.0      Portland                        NaT
9      Jack  19.000000   84.0       Phoenix                        NaT
10    Frank  20.894737   92.0   Los Angeles 2026-06-18 14:48:35.126842
11    Grace  21.000000   80.0         Miami 2026-06-17 14:48:35.126924
12    Heidi  22.000000    NaN       Houston 2026-06-16 14:48:35.126928
13     Ivan  24.000000   93.0       Phoenix 2026-06-15 14:48:35.126930
14     Judy  20.000000   90.0        Dallas 2026-06-14 14:48:35.126932
15    Kevin  22.000000   73.0           NaN 2026-06-13 14:48:35.126933
16     Liam  22.000000   77.0        Austin 2026-06-12 14:48:35.126935
17      Mia  24.000000   93.0  Jacksonville 2026-06-11 14:48:35.126936
18     Noah  19.000000   72.0      Columbus 2026-06-10 14:48:35.126938
19   Olivia  20.000000   91.0     Charlotte 2026-06-09 14:48:35.126939

# 2. Load an Excel file

In [59]:
!pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\isabe\miniconda3\envs\dab\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\isabe\miniconda3\envs\dab\Lib\site-packages (from openpyxl) (2.0.0)

In [60]:
# 1. Basic import
# You may get the below error:
# ImportError: `Import openpyxl` failed.  Use pip or conda to install the openpyxl package.
# !pip install openpyxl
df = pd.read_excel('Sales_Data.xlsx)

SyntaxError: unterminated string literal (detected at line 5) (2695947346.py, line 5)

In [61]:
df

       Name        Age  Grade          City             EnrollmentDate
0     Alice  20.000000   85.0        Boston                        NaT
1       Bob  19.000000   92.0      New York                        NaT
2   Charlie  21.000000   78.0       Chicago                        NaT
3     Diana  20.000000   88.0        Boston                        NaT
4       Eve  22.000000   95.0       Seattle                        NaT
5     Frank  19.000000   82.0         Miami                        NaT
6     Grace  21.000000   90.0        Denver                        NaT
7     Henry  20.000000   76.0        Austin                        NaT
8      Iris  22.000000   89.0      Portland                        NaT
9      Jack  19.000000   84.0       Phoenix                        NaT
10    Frank  20.894737   92.0   Los Angeles 2026-06-18 14:48:35.126842
11    Grace  21.000000   80.0         Miami 2026-06-17 14:48:35.126924
12    Heidi  22.000000    NaN       Houston 2026-06-16 14:48:35.126928
13     Ivan  24.000000   93.0       Phoenix 2026-06-15 14:48:35.126930
14     Judy  20.000000   90.0        Dallas 2026-06-14 14:48:35.126932
15    Kevin  22.000000   73.0           NaN 2026-06-13 14:48:35.126933
16     Liam  22.000000   77.0        Austin 2026-06-12 14:48:35.126935
17      Mia  24.000000   93.0  Jacksonville 2026-06-11 14:48:35.126936
18     Noah  19.000000   72.0      Columbus 2026-06-10 14:48:35.126938
19   Olivia  20.000000   91.0     Charlotte 2026-06-09 14:48:35.126939

In [62]:
?pd.read_excel

In [63]:
# 2. # If your Excel file has multiple sheets, specify the sheet
df = pd.read_excel('Sales_Data.xlsx', sheet_name='January')

In [64]:
df

          Date Region  Product  Units_Sold  Revenue    Month
0   2025-01-01   East   Laptop          33  1185.47  January
1   2025-01-02   West   Tablet          39  2737.15  January
2   2025-01-03   West    Phone          25  2281.43  January
3   2025-01-04   East    Phone          32  1762.67  January
4   2025-01-05  North   Tablet          34  2148.43  January
5   2025-01-06   West    Phone          16   896.24  January
6   2025-01-07  South    Phone          35  2252.04  January
7   2025-01-08  South   Laptop           2  3356.70  January
8   2025-01-09  North   Laptop          19  2541.82  January
9   2025-01-10  North   Laptop          23   984.60  January
10  2025-01-11   West    Phone           7  3091.30  January
11  2025-01-12   East   Laptop          40   994.27  January
12  2025-01-13  South   Tablet           8  4659.21  January
13  2025-01-14   East  Monitor           2  4697.84  January
14  2025-01-15   East  Monitor          15  3393.65  January
15  2025-01-16   East  Monitor          13  3347.45  January
16  2025-01-17   East   Tablet           5   517.22  January
17  2025-01-18   West   Laptop          50  4059.23  January
18  2025-01-19   West  Monitor          34  1980.08  January
19  2025-01-20   West   Tablet          31  1222.49  January

# 3. Load a database
It requires the package SQLAlchemy

In [65]:
# Install SQLAlchemy
# !pip install sqlalchemy
! pip install sqlalchemy

Requirement already satisfied: sqlalchemy in C:\Users\isabe\miniconda3\envs\dab\Lib\site-packages (2.0.50)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\isabe\miniconda3\envs\dab\Lib\site-packages (from sqlalchemy) (4.15.0)

In [66]:
from sqlalchemy import create_engine

In [67]:
# 1. Create the engine
engine = create_engine('sqlite:///bike_orders_database.sqlite')

In [70]:
# 2. Read the data directly using the engine
# You can pass the engine directly to read_sql
df = pd.read_sql('SELECT * FROM bikes', engine, index_col='index')

In [71]:
df

,bike.id,model,description,price
index,,,,
0,1,Supersix Evo Black Inc.,Road - Elite Road - Carbon,12790
1,2,Supersix Evo Hi-Mod Team,Road - Elite Road - Carbon,10660
2,3,Supersix Evo Hi-Mod Dura Ace 1,Road - Elite Road - Carbon,7990
3,4,Supersix Evo Hi-Mod Dura Ace 2,Road - Elite Road - Carbon,5330
4,5,Supersix Evo Hi-Mod Utegra,Road - Elite Road - Carbon,4260
...,...,...,...,...
92,93,Trail 5,Mountain - Sport - Aluminum,815
93,94,Catalyst 1,Mountain - Sport - Aluminum,705
94,95,Catalyst 2,Mountain - Sport - Aluminum,585
95,96,Catalyst 3,Mountain - Sport - Aluminum,480
96,97,Catalyst 4,Mountain - Sport - Aluminum,415